"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
/*
 * @Author: zml
 * @Date: 2022-03-04 14:54:52
 * @LastEditTime: 2022-03-07 16:39:47
 */
const _1 = __importDefault(require("."));
let str = `{
  "data": {
    "queueInfo": null,
    "shareMessage": null,
    "switchButton": [
      {
        "value": 1,
        "key": "modify_info",
        "content": ""
      },
      {
        "value": 1,
        "key": "share_order",
        "content": ""
      },
      {
        "value": 1,
        "key": "cancel_order",
        "content": ""
      },
      {
        "value": 1,
        "key": "once_again",
        "content": ""
      },
      {
        "value": 1,
        "key": "subscribe_msg",
        "content": ""
      },
      {
        "value": 1,
        "key": "remind_order",
        "content": ""
      }
    ],
    "orderInfo": {
      "receiverVphone": "",
      "deliveryDistance": 1,
      "senderGroupBuilding": "",
      "userOrderTime": 0,
      "acceptRidingDistance": 0,
      "userAccountVphone": "",
      "isNightSend": 0,
      "receiverPhone": "13608349097",
      "riderScheduleType": 0,
      "apiVersion": 17,
      "overflowExpectTime": 0,
      "coupons": [],
      "scanPayResult": "",
      "originalPayMoney": 1,
      "latestArriveTime": "",
      "receiverLng": "116.2977",
      "ruleId": 1100135,
      "receiverAoiId": "",
      "brand": "顺丰急送",
      "distributionMode": 0,
      "orderInfoVersion": 3,
      "wxOriginalApp": "",
      "pickUpDeptCode": "",
      "isModifying": 0,
      "senderModifiableNum": 0,
      "dishNum": 1,
      "isHighFigure": 0,
      "sfWantedCode": [],
      "dwBranchesFromType": 0,
      "realPayMoney": 1,
      "isColdTransportOrder": 0,
      "startDistriTime": "",
      "isInsured": 0,
      "riderSupplierId": "",
      "familyParentSfBillId": "",
      "belongsCityId": 111000000,
      "lbsType": 2,
      "riderId": "",
      "timeoutCompensateType": 0,
      "isPreAccept": 0,
      "assessmentHomeTime": 0,
      "userPayTime": 1634624581,
      "unitId": 0,
      "orderEndTime": 0,
      "isHasTip": 0,
      "orderThirdFrom": "",
      "settlementType": 2,
      "lineupTime": 0,
      "isLimitDelivered": 0,
      "originalDistance": 1,
      "totalPayMoney": 1,
      "expectPickupTime": 0,
      "dubiousInfo": {
        "score": 30,
        "level": 0
      },
      "isNeedFilebag": 0,
      "sfConsigneeEmpCode": "",
      "isRemote": 0,
      "apiReceiverLng": "116.2977",
      "userId": 100875404,
      "payTypeName": "寄付现结|微信",
      "isPersonDirect": 0,
      "createTime": "2021-10-19 14:22",
      "gratuityDetail": [],
      "senderDeptName": "",
      "claimValue": {
        "claimType": 1,
        "claimRange": [
          0,
          500
        ]
      },
      "customerCodePhone": 0,
      "originalGratuityMoney": 0,
      "signReceiptOrderType": 0,
      "serviceType": "1",
      "autoCancelTime": 1634627569,
      "wlType": 1,
      "groupId": "",
      "couponsTotalFee": 0,
      "invoiceAmount": 0,
      "senderDeptPhone": "",
      "deliverType": 2,
      "senderDeptCode": "",
      "isBack": 0,
      "riderPickupTime": 0,
      "costTime": "",
      "isOrderEncryption": 0,
      "appId": 1509208735,
      "isGetPoint": 0,
      "receiverDeptPhone": "",
      "productTypeName": "文件",
      "shopId": 3244606424177,
      "bmsShopName": "",
      "acceptNum": 0,
      "originalShopAddress": "",
      "isOldCashorder": 0,
      "stationId": 0,
      "finishTime": 1634624581,
      "riderSettlementDistance": 1,
      "senderDeptLng": "",
      "jianTotalFee": 0,
      "abnormalType": 0,
      "isNiaochaoOrder": 0,
      "chargeBillId": "",
      "locAssessmentTime": 0,
      "priceModel": 2,
      "tcUcode": "",
      "deliveryDeptCode": "",
      "riderName": "",
      "isStrOrder": 0,
      "receiverAddress": "长春桥路17号 北京市海淀区人民政府 ",
      "userOrderId": "C20211019000039294",
      "isRealNameCity": 1,
      "receiverDeptAddress": "",
      "isNecessar": 0,
      "userAccountPhone": "13608349097",
      "paymentMethod": 1,
      "isRejectFee": 0,
      "orderFrom": 5,
      "shopPicUrl": "",
      "isSelfSms": 0,
      "realnameVerifyType": 1,
      "isCrossCity": 0,
      "isReverseOrder": 0,
      "senderLat": "39.959893",
      "lcId": 6,
      "beforeCancelStatus": 0,
      "openId": "",
      "multiPickupInfo": [],
      "valueAddedFee": "",
      "orgAbnormalType": 0,
      "orderChannel": 5000000,
      "handoverCode": "",
      "priceRuleUrl": "https://shopic.sf-express.com/crm/common/nologincheckrender/product/crm/page/billrule?city_id=111000000&user_id=100875404&product_type=12&city_rule_id=1100135",
      "agentMode": 10,
      "riderVphone4account": "",
      "isBigOrder": 0,
      "beginTimeUser": 1634624569,
      "isModifyInsured": 0,
      "pushTime": 1634624569,
      "pointSelect": 0,
      "isUseHjCard": 0,
      "deliveryDistanceMeter": 1,
      "orderVer": 0,
      "isAppointmentCharge": 0,
      "isPioneerRider": 0,
      "receiverDeptLat": "",
      "weightLimit": 10000,
      "isSinkCity": 0,
      "verifyCodeType": 3,
      "dwGuid": "",
      "priceDistance": 1,
      "gratuityCouponFee": "0",
      "receiverModifiableNum": 0,
      "apiReceiverLat": "39.959893",
      "signNodeInfo": [],
      "pickupCode": 2671,
      "sourceName": "顺丰同城急送小程序",
      "isChangedAddress": 0,
      "cxEmpCode": 0,
      "pickupPic": [],
      "dishTypeNum": 1,
      "shopExpectTime": "",
      "expectDeliveryTime": "15:22",
      "orderType": 7,
      "isCandaoJuhe": 0,
      "senderModifiableTotalNum": 3,
      "senderAddress": "长春桥路17号 北京市海淀区人民政府 ",
      "isUseGratuityCoupon": 0,
      "isCanModify": 0,
      "orderId": "3428056184245106177",
      "dishTime": 0,
      "refundToken": "",
      "wxToken": "",
      "cityId": 111000000,
      "aggregationCancelFee": 0,
      "isCoreAoi": 0,
      "balanceToPayAmount": 0,
      "returnFlag": 1,
      "senderName": "day",
      "payType": 1,
      "expectFasterTime": 0,
      "sfUcode": "",
      "goodsPicUrl": "",
      "receiverDetail": {
        "receiverAddress": "长春桥路17号 北京市海淀区人民政府 ",
        "number": "",
        "receiverPhone": "13608349097",
        "receiverChangeAddress": "",
        "street": "长春桥路17号",
        "receiverName": "day",
        "receiverLng": "116.2977",
        "receiverLat": "39.959893",
        "building": "北京市海淀区人民政府"
      },
      "payBillIdList": [
        "2021101902308360031"
      ],
      "ridingDistance": 1,
      "receiverDeptCode": "",
      "declaredValue": 0,
      "firstAcceptTime": "",
      "extOrderFlag": 0,
      "gratuityFee": "0",
      "fengchaoPickupCode": "",
      "pictureUrls": [],
      "expectNum": 0,
      "signPicTime": 0,
      "riderVphone4sender": "",
      "originalShopName": "",
      "isLdpTransship": 0,
      "isDeliveredPhoto": 0,
      "senderDeptLat": "",
      "senderPhone": "13608349097",
      "isOrderDemotion": 0,
      "isFoodDelay": 0,
      "receiverAoiCode": "",
      "isCrowd": 1,
      "directionType": 4,
      "sfProductCode": 0,
      "thirdFromOrderType": 0,
      "isScanPay": 0,
      "goodsPrice": 1,
      "marketingFeeAll": 0,
      "brandId": 0,
      "sfLimitTypeCode": "",
      "toAoiId": 0,
      "isMultiPickup": 0,
      "prepayBillId": 0,
      "logisticType": 64,
      "groupBuilding": "",
      "dispatchType": 1,
      "aoiType": 3,
      "totalPrice": 1,
      "distanceLimit": 10000,
      "cChangedDistance": 0,
      "customerCode": "",
      "refundStatus": 0,
      "collectingPaymentMoney": 0,
      "receiptSfBillId": "",
      "completeCode": 9693,
      "vehicle": 0,
      "uniqCode": "crm-C20211019000039294",
      "isSendSms": 0,
      "originalOrderId": 0,
      "orderBusinessType": 2,
      "senderLng": "116.2977",
      "startTime": 1634624568,
      "toAoiName": "",
      "macdonaldTakenCode": [],
      "chargePriceList": "{\"shop_pay_price\":1,\"charges_detail\":{\"basic_fee\":1,\"basic\":1,\"over_distance\":0,\"over_weight\":0,\"sf_base_fee\":0,\"cancel_excess_fee\":0,\"special_time_fee\":0,\"vas_fee\":0,\"vas_fee_detail\":{\"packing_fee\":0,\"low_temp_fee\":0,\"take_goods_sms_fee\":0,\"services_fee\":0,\"insured\":{\"fee\":0,\"declared_price\":0},\"big_order\":{\"fee\":0,\"amount\":0},\"collection\":{\"fee\":0,\"price\":0},\"countersign\":{\"fee\":0,\"num\":0},\"person_direct_fee\":0,\"vehicle_car_fee\":0,\"appointment_fee\":0,\"file_bag_fee\":0,\"address_change_fee\":0,\"scan_pay_fee\":0,\"lineup_time_fee\":0,\"night_send_fee\":0,\"appointment_faster_fee\":0,\"accept_faster_fee\":0,\"expect_faster_fee\":0,\"resident_service_fee\":0},\"extra_fee\":0,\"extra_fee_detail\":{\"geography_fee\":0},\"gratuity_fee\":0,\"overflow_fee\":0},\"shop_deduction_price\":0,\"deduction_detail\":{\"deduction_fee\":0},\"is_ladder\":0,\"is_floor\":0,\"is_cancel_fee\":0,\"is_deduction_fee\":0,\"is_dubious\":0,\"is_insured_rule\":1,\"is_person_direct\":0,\"vehicle\":0,\"is_need_filebag\":0,\"is_big_order\":0,\"is_insured\":0,\"insured_ceiling_rule\":{\"start\":200000,\"end\":1000000,\"type\":\"2\",\"value\":\"1\",\"status\":1}}",
      "isTakePhoto": 0,
      "aggregationDeliveryFee": 0,
      "priceVersion": 602,
      "riderExtraFlag": 0,
      "gratuityCouponList": [],
      "holdPassBy": 0,
      "updateTime": 1634624581,
      "shiftInfo": [],
      "sfExpressTypeCode": "",
      "nightSendNeedFee": 0,
      "isCheckRiderHealth": 0,
      "isDwdailyDegrade": 0,
      "familyOrderList": [],
      "originalSettlementType": 2,
      "isScan": 0,
      "senderDeptAddress": "",
      "invoiceOwner": 100875404,
      "acceptDeliveryDistance": 0,
      "isTest": 1,
      "grabDuration": 0,
      "locExtra": {
        "capacityForId": 1000000006,
        "flag": 17,
        "dwAoiId": "",
        "limitOrderAmt": 0,
        "shopRealAoiId": 1000000006,
        "isDeliveredPhoto": 0,
        "isLimitCrowdOrderAmt": 2,
        "isSpecialCrowd": 0,
        "mealPush": 2,
        "isAutoFill": 0,
        "deliverType": 2,
        "isNewVersion": 1,
        "industryId": 0,
        "addOrderFlag": 26388279066624,
        "deliverProductType": 1,
        "isNecessar": 2,
        "capacityForType": 1,
        "crowdAoiId": 1000004764,
        "userRealAoiId": 1000000006,
        "isFillBlacklist": 0,
        "orderCrowdAoiId": 1000004764,
        "flatPeak": 2
      },
      "receiverDeptLng": "",
      "orderFlag": 12289,
      "receiverDeptName": "",
      "date": "20211019",
      "orderBatchId": "",
      "productValueRange": {
        "start": 0,
        "end": 500
      },
      "originalShopPhone": "",
      "senderVphone": "",
      "cancelingTime": 0,
      "pickupPicTime": 0,
      "sfCargoTypeCode": "",
      "isCallbackPhoto": 0,
      "explainRuleUrl": "https://shopic.sf-express.com/crm/common/nologincheckrender/product/crm/page/changeaddrexplain?city_id=111000000&user_id=100875404&product_type=12&city_rule_id=1100135",
      "orderTime": 1634624569,
      "scanPayMoney": 0,
      "isUserFirstCreate": 0,
      "tcCard": [],
      "overflowTip": "当前运力紧张，骑士响应可能受影响，请耐心等待",
      "promiseDeliveryTime": 60,
      "confirmMoneyTime": 0,
      "senderDetail": {
        "senderPhone": "13608349097",
        "senderLat": "39.959893",
        "number": "",
        "senderAddress": "长春桥路17号 北京市海淀区人民政府 ",
        "senderName": "day",
        "street": "长春桥路17号",
        "senderLng": "116.2977",
        "building": "北京市海淀区人民政府",
        "senderChangeAddress": ""
      },
      "outPaySerialNum": "",
      "receiverLat": "39.959893",
      "jian": [],
      "paotuiProductDetail": {
        "goodsDetail": null
      },
      "riderPhone": "",
      "agentName": "自营",
      "timeoutCompensateMoney": 0,
      "isAggregatingOrder": 0,
      "expectTimeOriginal": 0,
      "pickupType": 2,
      "signPicUrl": "",
      "receiverModifiableTotalNum": 3,
      "orderIsPay": true,
      "prepareTime": 0,
      "riderDetail": {
        "phone": "",
        "name": "",
        "isVirtual": 0,
        "virtual4rider": "13608349097"
      },
      "isDubious": 0,
      "isPlatformShop": 0,
      "senderDeptTime": "",
      "isAggregationOrder": 0,
      "shopIdentityCard": "",
      "senderGroupFloor": "",
      "evaluationStatus": 0,
      "evaluationChannel": "",
      "riderData": [],
      "groupFloor": "",
      "agentId": 0,
      "supplierId": 0,
      "receiverDeptTime": "",
      "convenienceStoreCode": "",
      "beginTimeLoc": 1634624569,
      "exRider": [],
      "sfBillId": "SF6509487837187",
      "orderStatus": 6000,
      "remark": "",
      "payState": 3,
      "familyOrderType": 0,
      "isCashorder": 0,
      "wishList": "",
      "expectFinishTime": 1634628168,
      "newKfc": 0,
      "cityName": null,
      "distanceType": 1,
      "appointmentFasterTime": 0,
      "priceRuleBusinessType": 3,
      "productType": 12,
      "holdCancelBy": 0,
      "abnormalLogisticDetail": [],
      "productDetail": {
        "productId": 12,
        "productName": "文件"
      },
      "sfProductName": "",
      "isEcoPackaging": 0,
      "receiverName": "day",
      "receiptPicUrl": "",
      "payCardId": 0,
      "deliveryType": 1,
      "cardType": 0,
      "familyOrderNum": 0,
      "isCandaoOrder": 0,
      "holdState": 0,
      "originalUserPhone": "",
      "weightGram": "1",
      "originExpectTime": 1634628168,
      "deliveredPic": [],
      "orderIndex": "13608349097",
      "riderVphone": "",
      "sfServiceCode": [],
      "aoiId": 1000001925,
      "payStatus": 1,
      "receiveUserMoney": 0
    },
    "signNodeInfo": [],
    "topFeed": {
      "subtitle": "",
      "title": "骑士正在抢单",
      "content": "如15:12前无骑士接单，订单将被取消"
    },
    "orderInfoList": [
      {
        "title": "订单编号",
        "key": "order_id",
        "content": {
          "value": "3428056184245106177"
        },
        "desc": ""
      },
      {
        "title": "运费金额",
        "key": "shop_pay_price",
        "content": {
          "value": "0.01元"
        },
        "desc": ""
      },
      {
        "title": "支付方式",
        "key": "pay_type_name",
        "content": {
          "value": "寄付现结|微信"
        },
        "desc": ""
      },
      {
        "title": "物品信息",
        "key": "product_type_name",
        "content": {
          "value": "文件、1公斤"
        },
        "desc": ""
      },
      {
        "title": "预计送达",
        "key": "expect_finish_time",
        "content": {
          "value": "2021-10-19 15:22"
        },
        "desc": ""
      },
      {
        "title": "配送距离",
        "key": "delivery_distance",
        "content": {
          "value": "0公里"
        },
        "desc": ""
      },
      {
        "title": "备注信息",
        "key": "remark",
        "content": {
          "value": ""
        },
        "desc": ""
      }
    ],
    "switchButtonPay": [
      {
        "content": "",
        "key": "add_gratuity",
        "value": 1
      }
    ],
    "errandInfo": [
      {}
    ],
    "chargePriceList": {
      "shopPayPrice": "0.01",
      "chargesDetail": {
        "hasDiscount": [
          {
            "price": "0.01元",
            "subtitle": "",
            "iconUrl": "https://crm-1258916733.cos.ap-shanghai.myqcloud.com/7b/6a/2ca6e16252b86361e6486dc7f191ab87/money.png",
            "title": "基础配送费",
            "fontColor": 0
          }
        ],
        "noDiscount": []
      }
    }
  },
  "errno": 0,
  "errmsg": "操作成功",
  "st": 1634624692,
  "is_degrade": false,
  "lid": "658072022622888675"
}`;
console.log((0, _1.default)(str, { startNode: 'orderInfo', name: 'type' }));
//# sourceMappingURL=test.js.map